### PR TITLE
add: sanity support and schema definition

### PR DESCRIPTION
**Pull request by wizaye**
This PR introduces the following updates:

- Integrated **Sanity** for content management.
- Defined schemas for:
  - **Product**: To manage product details.
  - **Invoice**: To handle invoice-related data.
  - **Customer**: To maintain customer information.

### Next Steps
The next phase will focus on:

1. Defining relationships between the **Product**, **Invoice**, and **Customer** schemas.
2. Adapting the schema relationships and data structure to fit Biocyte Therapeutics' business use case.

These tasks will be addressed in a separate issue.

### CODE REVIEW

**Comment by wizaye** [comment]
@javatcoding1 @SaiHitesh77 @SaiKarthikeya-234 please check the pr and do note the newer milestones in the issues tab

**Review by javatcoding1 — COMMENTED** [review]
I will let you know after a detailed review of the schema.

**Comment by wizaye** [comment]
> I will let you know after a detailed review of the schema.

@javatcoding1 reply?

**Comment by javatcoding1** [comment]
5cc0516f-6d53-4cc2-b4bc-b29033acf15a
All these fields need to be added to the schema before we can merge the pull request.

**Comment by wizaye** [comment]
> 5cc0516f-6d53-4cc2-b4bc-b29033acf15a All these fields need to be added to the schema before we can merge the pull request.

merge this pr and start working on the invoice schema @javatcoding1 without merging the code base we cant proceed

**Comment by wizaye** [comment]
@javatcoding1 @SaiHitesh77 @SaiKarthikeya-234 please maintain a private repo fork of this dashboard. I will be adding a branch protection and dropping all the branches on this repo. Please make a note of this

**Pull request merged**
