### PR TITLE
added types

### PR DESCRIPTION
**Pull request by javatcoding1**
Added the all the required types in the types folder

### CODE REVIEW

**Comment by wizaye** [comment]
@javatcoding1 did you test the website before raising the pr? 
Do let me know

**Review by wizaye — COMMENTED** [review]
why did you add icon in customer.d.ts ?

**Comment by javatcoding1** [comment]
@wizaye  yes i tested the website

**Comment by wizaye** [comment]
@javatcoding1 ok im merging the pr into main

**Comment by javatcoding1** [comment]
i removed the icon from the customer.d.ts

**Comment by wizaye** [comment]
> i removed the icon from the customer.d.ts

Noted , Merged the PR!
please note @SaiHitesh77 @SaiKarthikeya-234  make sure to sync your forks with the main when making changes :)

**Pull request merged**
